version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - ./app/:/var/www/symfony_project
    working_dir: /var/www/symfony_project
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: symfony_web_proxy
    volumes:
      - ./app:/var/www/symfony_project
      - ./nginx/default.conf/:/etc/nginx/conf.d/default.conf
    ports:
      - "9090:80"
    depends_on:
      - app
  
  db:
    image: mysql:8.0
    container_name: my_sql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3406:3306"
    volumes:
      - ./db_data:/var/lib/mysql
  
volumes:
  db_data: